spring:
  application:
    name: zipkin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka/, http://localhost:5002/eureka/, http://localhost:5003/eureka/

server:
  port: 7001
