version: '3'
services:
  sys:
      image: tjffy/sys:0.0.1-SNAPSHOT
      ports:
        - "8100:8100"
      container_name: sys
      volumes:
        - /etc/localtime:/etc/localtime
      command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=dev", "-jar", "/app.jar"]
      links:
        - zipkin