spring:
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  retryable: true
  routes:
    sys:
      sensitiveHeaders: "*"

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 6000
  ConnectTimeout: 3000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka/