spring:
  application:
    name: sys
  zipkin:
    base-url: http://localhost:7001
# 采样比例为1.0，也就是全部都需要
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka/

#logging:
#  config: classpath:logback.xml

